import { defineConfig, loadEnv } from 'vite'
import type { Plugin, ViteDevServer } from 'vite'
import react from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'
import type { IncomingMessage, ServerResponse } from 'node:http'
import fs from 'node:fs'
import path from 'node:path'
import { pathToFileURL } from 'node:url'

// Helper to parse and load .env files into process.env
function loadDotEnv(filePath: string) {
  try {
    if (fs.existsSync(filePath)) {
      const content = fs.readFileSync(filePath, 'utf-8');
      for (const line of content.split('\n')) {
        const trimmed = line.trim();
        if (trimmed && !trimmed.startsWith('#')) {
          const index = trimmed.indexOf('=');
          if (index !== -1) {
            const key = trimmed.substring(0, index).trim();
            let val = trimmed.substring(index + 1).trim();
            if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
              val = val.substring(1, val.length - 1);
            }
            process.env[key] = val;
          }
        }
      }
    }
  } catch (err) {
    console.error(`Failed to load ${filePath}:`, err);
  }
}

// Load environment variables from .env, .env.local, and vercel.json
loadDotEnv(path.resolve(process.cwd(), '.env'));
loadDotEnv(path.resolve(process.cwd(), '.env.local'));

try {
  const vercelJsonPath = path.resolve(process.cwd(), 'vercel.json');
  if (fs.existsSync(vercelJsonPath)) {
    const vercelConfig = JSON.parse(fs.readFileSync(vercelJsonPath, 'utf-8'));
    if (vercelConfig && vercelConfig.env) {
      for (const [key, val] of Object.entries(vercelConfig.env)) {
        if (val) {
          process.env[key] = val as string;
        }
      }
    }
  }
} catch (err) {
  console.error('Failed to load environment variables from vercel.json:', err);
}

// https://vite.dev/config/
export default defineConfig(async ({ mode }) => {
  const plugins = [react(), tailwindcss()];
  try {
    // @ts-expect-error optional source-tags plugin generated by the deploy toolchain
    const m = await import('./.vite-source-tags.js');
    plugins.push(m.sourceTags());
  } catch {
    /* optional */
  }

  // Serverless API Handler emulation middleware
  interface ApiRequest extends IncomingMessage {
    query: Record<string, string>;
    body?: unknown;
  }

  interface ApiResponse extends ServerResponse {
    status: (code: number) => ApiResponse;
    json: (data: unknown) => ApiResponse;
  }

  type NextFn = (err?: unknown) => void;

  const apiMiddlewarePlugin: Plugin = {
    name: 'api-serverless-middleware',
    configureServer(server: ViteDevServer) {
      server.middlewares.use(async (req: IncomingMessage, res: ServerResponse, next: NextFn) => {
        if (req.url && req.url.startsWith('/api/')) {
          const apiReq = req as ApiRequest;
          const apiRes = res as ApiResponse;
          const url = new URL(req.url, 'http://localhost');
          const routeName = url.pathname.replace(/^\/api\//, '');
          const parts = routeName.split('/');
          
          let apiFile = '';
          const exactPath = path.resolve(process.cwd(), 'api', `${routeName}.js`);
          if (fs.existsSync(exactPath)) {
            apiFile = exactPath;
          } else if (parts.length >= 2) {
            const dynamicPath = path.resolve(process.cwd(), 'api', parts[0], '[id].js');
            if (fs.existsSync(dynamicPath)) {
              apiFile = dynamicPath;
            }
          }
          if (!apiFile) {
            const segmentPath = path.resolve(process.cwd(), 'api', `${parts[0]}.js`);
            if (fs.existsSync(segmentPath)) {
              apiFile = segmentPath;
            }
          }

          if (apiFile) {
            try {
              const fileUrl = pathToFileURL(apiFile).href;
              const module = await import(fileUrl + '?t=' + Date.now());
              const handler = module.default;

              // Parse query parameters
              apiReq.query = Object.fromEntries(url.searchParams.entries());
              if (parts.length >= 2 && !apiReq.query.id) {
                apiReq.query.id = parts[1];
              }

              // Add Express/Vercel status helper
              apiRes.status = (code: number) => {
                apiRes.statusCode = code;
                return apiRes;
              };

              // Add Express/Vercel json helper
              apiRes.json = (data: unknown) => {
                apiRes.setHeader('Content-Type', 'application/json');
                apiRes.end(JSON.stringify(data));
                return apiRes;
              };

              // Parse body for mutations
              if (req.method === 'POST' || req.method === 'PUT' || req.method === 'DELETE') {
                let body = '';
                req.on('data', (chunk: Buffer | string) => {
                  body += chunk;
                });
                req.on('end', async () => {
                  try {
                    apiReq.body = body ? JSON.parse(body) : {};
                  } catch {
                    apiReq.body = body;
                  }
                  try {
                    await handler(apiReq, apiRes);
                  } catch (err) {
                    console.error('API Handler Execution Error:', err);
                    if (!apiRes.headersSent) {
                      apiRes.status(500).json({ error: err instanceof Error ? err.message : String(err) });
                    }
                  }
                });
              } else {
                await handler(apiReq, apiRes);
              }
            } catch (err) {
              console.error(`Error loading API handler: ${apiFile}`, err);
              if (!apiRes.headersSent) {
                apiRes.statusCode = 500;
                apiRes.setHeader('Content-Type', 'application/json');
                apiRes.end(JSON.stringify({ error: err instanceof Error ? err.message : String(err) }));
              }
            }
          } else {
            next();
          }
        } else {
          next();
        }
      });
    }
  };

  const env = loadEnv(mode, process.cwd(), ['VITE_', 'NEXT_PUBLIC_']);
  const processEnvDefines: Record<string, string> = {};
  for (const [key, value] of Object.entries(env)) {
    processEnvDefines[`process.env.${key}`] = JSON.stringify(value);
  }

  return {
    plugins: [...plugins, apiMiddlewarePlugin],
    envPrefix: ['VITE_', 'NEXT_PUBLIC_'],
    define: processEnvDefines,
    build: {
      target: 'es2022',
      cssCodeSplit: true,
      modulePreload: {
        polyfill: false,
      },
      rollupOptions: {
        output: {
          manualChunks(id: string) {
            if (!id.includes('node_modules')) return undefined;
            if (id.includes('framer-motion') || id.includes('/motion/')) return 'motion';
            if (id.includes('lucide')) return 'icons';
            if (
              id.includes('/react') ||
              id.includes('react-dom') ||
              id.includes('react-router') ||
              id.includes('scheduler')
            ) {
              return 'vendor';
            }
            return 'vendor';
          },
        },
      },
    },
  };
})
